### ISSUE TITLE
Bottom Navigation view with viewpager not getting callback

### ISSUE THREAD

**Issue by urvish91** [PHELAT/NavigationResult#1]
When bottom navigationview with viewpager and then from each tab fragment if we use the navigation then not calling "onFragmentResult" we have different navhostIds for each tab. and I am updating the navHostId as you instructed. 

Kindly help me to solve this problem.

**Comment by deeptimay-Quickride** [comment]
NavigationResult onFragmentResult not getting called for bottom navigationview. I have single nav host i have follow all 5 steps.
