### ISSUE TITLE
How it can be used with Dagger2?

### ISSUE THREAD

**Issue by sahusatyam27** [PHELAT/NavigationResult#2]
How can it be used with Dagger2.

**I have BaseFragment which extends DaggerFragment, so how can i extend your BundleFragment?**

**Comment by PHELAT** [comment]
There is workaround for this, I'm also planning to fix this extension problem for the next release.
So currently to fix this, you can copy DaggerFragment's behavior into your BaseFragment:
```kotlin
abstract class BaseFragment : BundleFragment(), HasAndroidInjector {

    @Inject
    lateinit var androidInjector: DispatchingAndroidInjector<Any>

    override fun onAttach(context: Context) {
        AndroidSupportInjection.inject(this)
        super.onAttach(context)
    }

    override fun androidInjector(): AndroidInjector<Any> {
        return androidInjector
    }

}
```

**Comment by sahusatyam27** [comment]
This requires a lot of changes in my base implementation of all Fragment classes, can you please add it into the extension.

**Comment by PHELAT** [comment]
Unfortunately this isn't possible, because not all of the NavigationResult users use `dagger-android` library in their projects.

**Comment by sahusatyam27** [comment]
Seems this library has restriction that if you use this library, you can't use dagger.

**Comment by PHELAT** [comment]
This is not true. I've already told you how to make it work with `dagger-android`.
