### ISSUE TITLE
NavigationResult, onFragmentResult not getting called for bottomNavigationView

### ISSUE THREAD

**Issue by deeptimay-Quickride** [PHELAT/NavigationResult#3]
NavigationResult onFragmentResult not getting called for bottomNavigationView. I have single nav host and I have followed all 5 steps.
I'm going to a fragment B then comming back to fragment A by **navigateUp** with request code and bundle. Fragment  A is a part of bottomNavigationView.

Will your solution wont work on bottomNavigationView ?

**Comment by PHELAT** [comment]
I'm not sure why you've closed your issue, did you manage to fix it?

**Comment by deeptimay-Quickride** [comment]
Yeah, I was doing a mistake. **navigate()** should be used from the library, I was using the default NavControler's navigate. Now it's working fine. Thanks
