### ISSUE TITLE
navigateUp function not found in java apps

### ISSUE THREAD

**Issue by Kreateyou** [PHELAT/NavigationResult#4]
I am using the java with this lib trying to access navigateUp(9292, bundle);  it can not find the method

**Comment by PHELAT** [comment]
This function is accessible through `NavigationKt` class for Java users. You can use it like this:
```java
NavigationKt.navigateUp(this, REQUEST_CODE, bundle);
```
In the example above, `this` is the instance of your fragment class.

**Comment by Kreateyou** [comment]
Thanks for this great product

**Comment by PHELAT** [comment]
I'm glad that you've found it useful.

**Comment by Kreateyou** [comment]
` NavigationKt.navigateUp(this,REQUEST_CODE , bundle); ` works ok but the **onFragmentResult** is not called
```
   @Override
    public void onFragmentResult(int requestCode, @NotNull Bundle bundle) {
        super.onFragmentResult(requestCode, bundle);
        Log.e("onFragmentResult","onFragmentResult Called");

    }
```

**Comment by PHELAT** [comment]
Are you using the `navigate` function of BundleFragment? Please make sure that you aren't using the one inside NavController class. Basically, in your starting point fragment you don't have to `findNavController` and instead call `navigate` function directly.

**Comment by Kreateyou** [comment]
Yes am calling navigate() from BundleFragment not from NavController

I basically have 3 fragment

```
CLASS_A extends BundleFragment{
  void onAction(){
     navigate(action_to_CLASS_B,bundle,CODE);
  }
}

CLASS_B extends BundleFragment{
  void onAction(){
     navigate(action_to_CLASS_C,bundle,B_REQUEST_CODE);
  }
 @Override
 public void onFragmentResult(int requestCode, @NotNull Bundle bundle) {
        super.onFragmentResult(requestCode, bundle);
        Log.e("onFragmentResult","onFragmentResult Called");

    }
}

CLASS_C extends BundleFragment{
  void onAction(){
     NavigationKt.navigateUp(this,B_REQUEST_CODE , bundle);
  }
}
```

**Comment by PHELAT** [comment]
I'll check to see what's the problem.

**Comment by Kreateyou** [comment]
Thanks so much

**Comment by PHELAT** [comment]
I've checked to see what's the problem and I couldn't find any issues regarding your use-case. I've made a sample branch called `triple-fragments` on this repository and you can check that out to see how to use this library with your use-case. The code that you may want look for is inside a file called `TripleFragments.kt`. You can also checkout the branch from this [link](https://github.com/PHELAT/NavigationResult/tree/triple-fragments).

**Comment by PHELAT** [comment]
I'm going to close this for now.
